repos:
-   repo: local
    hooks:
      - id: typehint
        name: Typehinting
        entry: mypy --config-file pyproject.toml app/
        stages: [push]
        language: system
        always_run: true
        pass_filenames: false
      - id: black
        name: Black code formatting
        entry: black app/ tests/
        stages: [commit]
        language: system
        always_run: true
        pass_filenames: false