[tool.mypy]
    python_version = "3.8"
    disallow_untyped_defs = true
    ignore_missing_imports = true
    no_implicit_optional = true
    warn_return_any = true
    show_error_codes = true
    warn_unused_ignores = true